databases:
  - name: kintai_db # Render上でのデータベースの名前
    databaseName: kintai_db_wad1 # PostgreSQL内部のデータベース名
    user: kintai_db_wad1_user # データベースユーザー名
    plan: free # 無料プラン（Free Planを使用している場合）

services:
  - type: web
    name: kintai # サービスの名前
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kintai_db
          property: connectionString # データベースの接続情報を自動で取得
      - key: RAILS_MASTER_KEY
        sync: false # Railsのマスターキーは手動で設定
      - key: WEB_CONCURRENCY
        value: 2 # 適切な並列処理数（変更可能）
