default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timezone: "Asia/Tokyo"

development:
  <<: *default
  database: rails_app_development
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: rails_app_test
  host: db
  username: postgres
  password: password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Renderが提供するDATABASE_URLを使用
