default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: rails_app_development
# test:
#   <<: *default
#   database: rails_app_test

# production:
#   <<: *default
#   database: rails_app_production
#   username: <%= ENV['POSTGRES_USERNAME'] %>
#   password: <%= ENV['POSTGRES_PASWSWORD'] %>
#   host: <%= ENV['POSTGRES_HOST'] %>
